name: push_notifications_app
description: App de prueba para notificaciones push

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP requests
  http: ^1.1.0
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  
  # Local notifications
  flutter_local_notifications: ^16.3.2
  
  # Biometric authentication
  local_auth: ^2.1.7
  
  # Storage
  shared_preferences: ^2.2.2
  
  # State management
  provider: ^6.1.1
  
  # Device info
  device_info_plus: ^9.1.1
  
  # Material icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true